### ISSUE TITLE
Vote for Color Scheme!

### ISSUE THREAD

**Issue by theSuiGenerisAakash** [TechUniv2018/ShopSocialFrontEnd#29]
**Which one?**

*First One*
<img width="1677" alt="screen shot 2018-03-11 at 23 58 17" src="https://user-images.githubusercontent.com/16731634/37257043-8374a808-2589-11e8-8d86-ac11f664ead1.png">

*Second One*
<img width="1675" alt="screen shot 2018-03-11 at 23 58 53" src="https://user-images.githubusercontent.com/16731634/37257044-842f3286-2589-11e8-91ae-72e40fb1c1d0.png">

**Comment by theSuiGenerisAakash** [comment]
Second One

**Comment by maheshhp** [comment]
First one with rounded corners for the cards!

**Comment by theSuiGenerisAakash** [comment]
Ram Prasad and Abhilash have voted for the second one.
