### ISSUE TITLE
Product display page

### ISSUE THREAD

**Issue by ananddeb23** [TechUniv2018/ShopSocialFrontEnd#4]
**What do we want?**
We need to set up the product display view for the customer to be able to view a specific product by id and be able to see the details and have the add to cart button

**How do we do it?**
We create the components which display the product after fetching from the backend via an API and use loaders to fill in the screen until the product data is available.

**How does the timeline look like?**
We aim to achieve the target by 02  March 2018.

**Improvement to existing style** #31 
Current styling is being updated based on suggestion in the demo, under the same issue.
Expected completion date: 15 March 2018.

**Comment by maheshhp** [comment]
Please follow uniform naming scheme for CSS classes

**Comment by theSuiGenerisAakash** [comment]
Apart from what Mahesh said, please take care of the warnings you encounter. There are way too many as of now.

**Comment by theSuiGenerisAakash** [comment]
Product Display page is unsalvageable.

Too many unnecessary and wrongly placed divs and centers.
