### ISSUE TITLE
Implementation and integration of cart with header/main web application

### ISSUE THREAD

**Issue by maheshhp** [TechUniv2018/ShopSocialFrontEnd#9]
**What is required?**

Cart operations like insert products, remove products etc. have to be integrated with redux.

**What should be implemented?**

Following operations related to cart have to be implemented as redux actions:
- [ ] Insert product to cart
- [ ] Delete product from cart
- [ ] Checkout and clear cart contents

**Timeline:**

We aim to achieve the implementation by ~8th Mar 2018~ 11th March, 2018.

**Comment by theSuiGenerisAakash** [comment]
Redux is R.I.P. Is everything else accomplished here?
